### ISSUE TITLE
'gradle pactVerify' command doesn't work as described

### ISSUE THREAD

**Issue by sheldon-white** [mstine/microservices-pact#7]
I get an error complaining that port 8080 is already in use:

garnet:/Users/swhite/workspaces/microservices/microservices-pact> gradle pactVerify
:microservices-pact-provider:startProvider

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.3.RELEASE)

2015-11-01 10:52:21.261  INFO 16767 --- [           main] i.p.m.pact.provider.Application          : Starting Application on garnet with PID 16767 (/Users/swhite/workspaces/microservices/microservices-pact/microservices-pact-provider/build/classes/main started by swhite in /Users/swhite/workspaces/microservices/microservices-pact/microservices-pact-provider)
2015-11-01 10:52:21.308  INFO 16767 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1e7c7811: startup date [Sun Nov 01 10:52:21 PST 2015]; root of context hierarchy
2015-11-01 10:52:21.824  INFO 16767 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver': replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2015-11-01 10:52:22.504  INFO 16767 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2015-11-01 10:52:22.747  INFO 16767 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2015-11-01 10:52:22.749  INFO 16767 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.20
2015-11-01 10:52:22.852  INFO 16767 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2015-11-01 10:52:22.852  INFO 16767 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1546 ms
2015-11-01 10:52:23.435  INFO 16767 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2015-11-01 10:52:23.439  INFO 16767 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2015-11-01 10:52:23.439  INFO 16767 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2015-11-01 10:52:23.684  INFO 16767 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1e7c7811: startup date [Sun Nov 01 10:52:21 PST 2015]; root of context hierarchy
2015-11-01 10:52:23.739  INFO 16767 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/foos],methods=[GET],params=[],headers=[],consumes=[],produces=[],custom=[]}" onto public org.springframework.http.ResponseEntity<java.util.List<io.pivotal.microservices.pact.provider.Foo>> io.pivotal.microservices.pact.provider.Application.foos()
2015-11-01 10:52:23.741  INFO 16767 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],methods=[],params=[],headers=[],consumes=[],produces=[],custom=[]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2015-11-01 10:52:23.742  INFO 16767 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],methods=[],params=[],headers=[],consumes=[],produces=[text/html],custom=[]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest)
2015-11-01 10:52:23.767  INFO 16767 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-11-01 10:52:23.768  INFO 16767 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-11-01 10:52:23.806  INFO 16767 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-11-01 10:52:23.878  INFO 16767 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-11-01 10:52:23.937 ERROR 16767 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Failed to start end point associated with ProtocolHandler ["http-nio-8080"]

java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:343)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:739)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:472)
	at org.apache.coyote.http11.Http11NioProtocol.start(Http11NioProtocol.java:81)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:986)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:237)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:186)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:149)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
...etc...

**Comment by roigamliel** [comment]
+1

**Comment by monisha-bhattacharya** [comment]
+1

**Comment by monisha-bhattacharya** [comment]
I was  trying this on Mac and I was only able to run this successfully by doing following additional steps :

1. Editing build.gradle as :

 task loadVersion {
        //ext.myVersion = new File("${versionFilePath}/number").text
    }

    task manifestFilter(type: Copy) {
        from 'manifest.yml'
        into 'versioned-manifest'
        expand(version: "0.0.1")
    }

2. Creating a number file . dir /microservices-pact :
echo 0.0.1 > number

3. creating following env variables :

PACT_FILE (set the path of where the pact json file Foo_Consumer-Foo_Provider.json exists)
VERSION_FILE_PATH (set the absolute path of where your number file was created)

4. According to readme after you start the provider jar, make sure it runs properly and then stop it and check if the port 8080 is free before trying the pactVerify step.
